# Generated by Django 5.1.7 on 2025-03-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_country_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="creamos_client_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
