# Generated by Django 5.1.7 on 2025-03-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_client_creamos_client_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField(max_length=255)),
                ("profile_id", models.IntegerField(max_length=255)),
                ("report_id", models.IntegerField(max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.client"
                    ),
                ),
            ],
        ),
    ]
