# Generated by Django 5.1.7 on 2025-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_cmlicense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmlicense",
            name="account_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cmlicense",
            name="profile_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cmlicense",
            name="report_id",
            field=models.IntegerField(),
        ),
    ]
